name: terraform-validate
on:
  pull_request:
    paths:
      - '**/*.tf'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        run: terraform init -backend=false || true
      - name: Terraform validate
        run: terraform validate || true
      - name: TFLint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
      - name: Checkov (Terraform)
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          quiet: true
